variables:
- group: container-registry
- name: imageName
  value: scraper-iprox
- name: tag
  value: $(imageName):$(echo $(Build.SourceVersion) | cut -c1-7)


- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |   
        echo 'Building docker container with tag: $(tag)'
        docker build -f $(Build.SourcesDirectory)/build-docker-image/Dockerfile -t $(tag) .
        docker tag $(tag) $(acr_url)/$(tag)
        echo 'Artifact is tagged as: "$(tag)"'
      displayName: 'Build docker-image'

    - script: |
        # Push to docker registry (Which one is based on branch)
        if [ $(branch) == 'main' ]; then
          docker login -u $(acr_username) -p $(acr_password) $(acr_url)
          echo 'Pushing artifact to: "$(acr_url)"'
          docker push $(acr_url)/$(tag)
        else
          docker login -u $(acr_username) -p $(acr_password) $(acr_url)
          echo 'Pushing artifact to: "$(acr_url)"'
          docker push $(acr_url)/$(tag)
        fi
      displayName: 'Push docker-image to registry'