variables:
- group: container-registry
- name: imageName
  value: scraper-iprox
- name: tag
  value: $(imageName):$(echo $(Build.BuildNumber) | cut -c1-7)
- name: unittestPassed
  value: false

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |   
        echo 'Building docker container with tag: $(tag)'
        docker build -f $(Build.SourcesDirectory)/build-docker-image/Dockerfile -t $(tag) .
      displayName: 'Build docker-image'

    - script: | 
        docker run -e UNITTEST=true $(tag) && unittestPassed=true
        echo "unittestPassed: $(unittestPassed)"
        # if [ $(unittestPassed) == 'false' ]; then
        #   exit 1
        # fi
      displayName: 'Run unittests'

    - script: |
        #echo "BuildId: $(Build.BuildId)"
        #echo "BuildNumber: $(Build.BuildNumber)"
        #echo "SourceVersion: $(Build.SourceVersion)"
        docker tag $(tag) $(acr_url)/$(tag)
        echo 'Artifact is tagged as: "$(tag)"'
      displayName: 'Tag docker image'

    - script: |
        docker login -u $(acr_username) -p $(acr_password) $(acr_url)
        echo 'Pushing artifact to: "$(acr_url)"'
        docker push $(acr_url)/$(tag)
      displayName: 'Push docker image to registry'