variables:
- group: container-registry
- name: imageName
  value: scraper-iprox
- name: tag
  value: $(imageName):$(echo $(Build.SourceVersion) | cut -c1-7)
- name: unittestPassed
  value: false

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |   
        echo 'Building docker container with tag: $(tag)'
        docker build -f $(Build.SourcesDirectory)/build-docker-image/Dockerfile -t $(tag) .
      displayName: 'Build docker-image'

    - script: | 
        docker run -e UNITTEST=true $(tag) && unittestPassed=true
        # if [ $(unittestPassed) == 'false' ]; then
        #   exit 1
        # fi
      displayName: 'Unittests'

    - script: |
        # Tag image
        docker tag $(tag) $(acr_url)/$(tag)
        echo 'Artifact is tagged as: "$(tag)"'
              
        # Push to docker registry 
        if [ $(branch) == 'main' ]; then
          docker login -u $(acr_username) -p $(acr_password) $(acr_url)
          echo 'Pushing artifact to: "$(acr_url)"'
          docker push $(acr_url)/$(tag)
        else
          docker login -u $(acr_username) -p $(acr_password) $(acr_url)
          echo 'Pushing artifact to: "$(acr_url)"'
          docker push $(acr_url)/$(tag)
        fi
      displayName: 'Tag and push docker-image to registry'