trigger: none
    
pool:
  vmImage: ubuntu-latest

variables:
- group: container-registry
- name: imageName
  value: scraper-iprox-unittest
- name: unittestPassed
  value: false

steps:
- script: |   
    echo 'Building docker container with tag: $(imageName)'
    docker build -f $(Build.SourcesDirectory)/build-docker-image/Dockerfile -t $(imageName) .
  displayName: 'Build docker image'

- script: | 
    docker run -e UNITTEST=true $(imageName) && echo "##vso[task.setvariable variable=unittestPassed;]true"
  displayName: 'Run unittests'

# Handling the result needs to be in a different step because only then variable wil be expanded
# See: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#macro-syntax-variables
- script: |    
    if [ $(unittestPassed) == 'false' ]; then
      exit 1
    fi    
  displayName: 'Fail pipeline if unittest result is false'