trigger:
  batch: true
  branches:
    include:
    - main

resources:
- repo: self

variables:
  - group: acr-ontwikkel 
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: $(docker-registry-service-connection)
  - name: imageRepository
    value: 'amsterdam-app-scraper-iprox'
  - name: containerRegistry
    value: $(container-registry)
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: tag
    value: '$(Build.BuildNumber)'
  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: pylintPassed
    value: false

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        export PYTHONPATH=$(Build.SourcesDirectory)
        python3 -m pip install pylint pylint_django
        python3 -m pip install -r requirements.txt
        pylint --rcfile ./.pylintrc $(find . -name '*.py' | grep -v -e venv -e migrations -e kladblok) && echo "##vso[task.setvariable variable=pylintPassed;]true"
      displayName: 'Running pylint'

    - script: |
        if [ $(pylintPassed) == 'false' ]; then
          exit 1
        fi
      displayName: 'Fail if code has been rated less then 10.0'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)